# kudos to dropwizard/dropwizard for the sample config! :)

language: java

install: echo "I trust Maven."

script: mvn verify

jdk:
    - oraclejdk7
    - openjdk7

branches:
    only:
        - master
        - develop
