# kudos to dropwizard/dropwizard for the sample config! :)

language: java

install: echo "I trust Maven."

script: mvn deploy --settings travis/settings.xml

jdk:
    - oraclejdk7

branches:
    only:
        - master
        - develop

env:
    global:
        - secure: mmRiOepYFtdARJMvJt6GF+MEuX6iXhnmGyi98WhqILS4kHmKx58LXZTwC5zzydd6pcBvkREWkhLryOdtM7REseljSkFIY/6I4hMzlrCsb8+SRpOB0ESsMGAEJ9apmV6tDw+HYumtE97ZcI9vNuVydxtSp9kTPEAqjumsbLs+kWw=
        - secure: iEqLk/aJLg+NHPIFBTBs1OFMsZg8c/xQsamOi8UbBztLc2TyK/wee0ATkSHcmFLI8ZLtAnjim34/E5EPs7n4QZD/z8Kt0pEXtCUVXf0qW5WgyWKAVrNW0JTv/Jbqy9wQKRZ4RkdkU9IA76LFWUGpsBYY69NtAjDDEERoE9b8NkM=
